language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - mysql
  - memcached

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  - PHALCON_VERSION="2.0.6"
  - PHALCON_VERSION="2.0.5"
  - PHALCON_VERSION="2.0.4"
  - PHALCON_VERSION="2.0.3"
  - PHALCON_VERSION="2.0.2"
  - PHALCON_VERSION="2.0.1"
  - PHALCON_VERSION="2.0.0"

install:
  - composer self-update
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - composer install

before_script:
  - cp ./tests/config/config.php.dist ./app/config/config.php
  - mysql -e 'CREATE DATABASE phosphorum CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
  - cat schemas/forum.sql | mysql phosphorum
  - (cd ./scripts/ && php random-entries.php > /dev/null)

after_script:
  - mysql -e 'DROP DATABASE forum;' -uroot

script:
  - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 --ignore=app/cache app/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
    - nikos@phalconphp.com
    - sadhooklay@gmail.com
