language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

env:
  - PHALCON_VERSION="2.1.x"
  - PHALCON_VERSION="phalcon-v2.0.9"
  - PHALCON_VERSION="phalcon-v2.0.8"
  - PHALCON_VERSION="phalcon-v2.0.7"
  - PHALCON_VERSION="phalcon-v2.0.6"
  - PHALCON_VERSION="phalcon-v2.0.5"
  - PHALCON_VERSION="phalcon-v2.0.4"

install:
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get() . PHP_EOL;'
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - java -jar selenium-server-standalone-2.48.2.jar -port 4444 >/dev/null 2>&1 &
  - sleep 5
  - cp ./tests/config/config.php.dist ./app/config/config.php
  - mysql -e 'CREATE DATABASE phosphorum CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
  - cat schemas/forum.sql | mysql phosphorum
  - (cd ./scripts/ && php random-entries.php > /dev/null)
  - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &
  - stty cols 160

after_script:
  - mysql -e 'DROP DATABASE phosphorum;' -uroot

script:
  - vendor/bin/phpcs --standard=PSR2 --colors --extensions=php --ignore=app/cache/*,app/config/* app/
  - vendor/bin/codecept build
  - vendor/bin/codecept run

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
    - nikos@phalconphp.com
    - serghei@phalconphp.com
