language: php

php:
  - 5.4
  - 5.5
  - 5.6

services:
  - memcached

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

env:
  - PHALCON_VERSION="2.1.x"
  - PHALCON_VERSION="phalcon-v2.0.10"
  - PHALCON_VERSION="phalcon-v2.0.9"
  - PHALCON_VERSION="phalcon-v2.0.8"
  - PHALCON_VERSION="phalcon-v2.0.7"
  - PHALCON_VERSION="phalcon-v2.0.6"
  - PHALCON_VERSION="phalcon-v2.0.5"

install:
  - wget http://selenium-release.storage.googleapis.com/2.48/selenium-server-standalone-2.48.2.jar
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b ${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g0 -O0 -std=gnu90"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j2 &> /dev/null && make --silent install)
  - phpenv config-add ./tests/_ci/phalcon.ini &> /dev/null
  - php --ri phalcon
  - travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs
  # PHP 5.4 issue
  - mkdir -p $HOME/bin
  - wget -O $HOME/bin/codecept.phar http://codeception.com/releases/2.1.6/php54/codecept.phar
  - chmod +x $HOME/bin/codecept.phar

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - java -jar selenium-server-standalone-2.48.2.jar -port 4444 >/dev/null 2>&1 &
  - sleep 5
  - cp ./app/config/config.example.php ./app/config/config.php
  - cp ./app/config/development.example.php ./app/config/development.php
  - cp ./.env.example ./.env
  - mysql -e 'CREATE DATABASE phosphorum CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;'
  - cat schemas/forum.sql | mysql phosphorum
  - php ./scripts/random-entries.php >/dev/null 2>&1 &
  - php -S 127.0.0.1:8000 -t public/ .htrouter.php >/dev/null 2>&1 &
  - stty cols 160

script:
  - vendor/bin/phpcs --standard=PSR2 --colors --extensions=php --ignore=app/cache/*,app/config/* app/
  # PHP 5.4 issue
  - 'if [ "$TRAVIS_PHP_VERSION" != "5.4" ]; then vendor/bin/codecept build && vendor/bin/codecept run; else $HOME/bin/codecept.phar build && $HOME/bin/codecept.phar run; fi'

notifications:
  email:
    recipients:
      - andres@phalconphp.com
      - eduar@phalconphp.com
      - nikos@phalconphp.com
      - serghei@phalconphp.com
    on_success: change
    on_failure: always
