version: '2'

services:
    application:
        build: opsfiles/containers/core
        container_name: forum_application
        volumes:
            - .:/var/www/forum
        tty: true

    elasticsearch:
        restart: always
        image: elasticsearch:2.3
        container_name: forum_elasticsearch
        ports:
            - "9200:9200"
            - "9300:9300"

    mysql:
        restart: always
        image: mysql:5.7
        container_name: forum_mysql
        ports:
            - "3306:3306"
        volumes:
            - ./schemas/forum.sql:/docker-entrypoint-initdb.d/forum.sql:ro
            - forum_mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: zforum
            MYSQL_USER: root
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

    php:
        image: phalconphp/php-fpm:7.0
        restart: always
        container_name: forum_php
        working_dir: /var/www/forum
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes_from:
            - application
        depends_on:
            - mysql
            - elasticsearch

    nginx:
        restart: always
        image: phalconphp/nginx:1.10
        container_name: forum_nginx
        ports:
            - "80:80"
            - "443:443"
        depends_on:
             - php
        volumes:
            - ./opsfiles/nginx.conf:/etc/nginx/sites-enabled/forum.conf:ro
        volumes_from:
            - application
        environment:
            # production | development | staging | testing
            APP_ENV: development

# docker volume create --name=forum_mysql
# docker volume create --name=forum_elasticsearch
volumes:
    forum_mysql:
        driver: local
    forum_elasticsearch:
        driver: local

# docker network create --driver bridge forum_nw
networks:
  default:
    external:
      name: forum_nw
